name: Android app tests in BrowserStack
on: [push, pull_request]
jobs:
  Tests-in-BrowserStack:
    runs-on: ubuntu-latest

    steps:
        - name: Pull the project into the runner
          uses: actions/checkout@v4
        - uses: actions/setup-node@v3
          with:
            node-version: '20.x'
        
        - name: Install
          run: npm install
        
        - name: Run tests
          env:
            BS_USER: ${{ secrets.BS_USER }}
            BS_KEY:  ${{ secrets.BS_KEY }}
          run: npx wdio config/wdio.android.bs.conf.js --spec app/android/ApiDemos-debug.apk
        
        #- uses: actions/upload-artifact@v1
        #  if: failure()
        #  with:
        #    name: logs
        #    path: logs

        - name: Upload reports
          uses: actions/upload-artifact@v3
          with:
            name: Test-Reports
            path: _view_shots
          if: always()        