name: Tests in Github
on: [push, pull_request]
jobs:
  Tests-in-Github-emulator:
    runs-on: macos-latest

    steps:
        - name: Pull into the runner
          uses: actions/checkout@v3
        - uses: actions/setup-node@v3
          with:
            node-version: 16
        
        - name: Install
          run:
            npm install
            npm install -g appium@next
            npx appium -v
            npx appium &>/dev/null &
            npx appium driver install uiautomator2

        - name: Run tests
          env:
            BS_USER: ${{ secrets.BS_USER }} #1/3
            BS_KEY: ${{ secrets.BS_KEY }}   #2/3
          uses: reactivecircus/android-emulator-runner@v2
          with:
            api-level: 29
            #api-level: 32
            #target: google_apis
            #arch: x86_64
            #profile: Nexus 6
            #script: npx wdio config/wdio.android.conf.js
            script: npx wdio config/wdio.android.bs.conf.js #3/3
        
        - name: Upload reports
          uses: actions/upload-artifact@v3
          with:
            name: Test reports
            path: _view_shots
          if: always()        